apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fritzy
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "warn"
  ACCOUNT_SERVICE_URL: "http://account-service:8080"
  CATALOG_SERVICE_URL: "http://catalog-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  RATE_LIMIT: "10000"
  CACHE_TTL: "1800"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: fritzy
type: Opaque
stringData:
  POSTGRES_USER: "prod_user"
  POSTGRES_PASSWORD: "CHANGE_ME_SECURE_PASSWORD"
  POSTGRES_DB: "fritzy_production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: fritzy
spec:
  replicas: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql-hpa
  namespace: fritzy
spec:
  minReplicas: 5
  maxReplicas: 20
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: graphql-pdb
  namespace: fritzy
spec:
  minAvailable: 3
