apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics
  namespace: fritzy
data:
  topics.sh: |
    #!/bin/bash
    KAFKA_BROKER="kafka-0.kafka-headless:9092"

    kafka-topics --create --if-not-exists --bootstrap-server $KAFKA_BROKER \
      --topic account.events --partitions 3 --replication-factor 3 \
      --config min.insync.replicas=2 \
      --config retention.ms=604800000

    kafka-topics --create --if-not-exists --bootstrap-server $KAFKA_BROKER \
      --topic order.events --partitions 3 --replication-factor 3 \
      --config min.insync.replicas=2 \
      --config retention.ms=604800000

    kafka-topics --create --if-not-exists --bootstrap-server $KAFKA_BROKER \
      --topic catalog.events --partitions 3 --replication-factor 3 \
      --config min.insync.replicas=2 \
      --config retention.ms=604800000

    kafka-topics --create --if-not-exists --bootstrap-server $KAFKA_BROKER \
      --topic order.created --partitions 3 --replication-factor 3 \
      --config min.insync.replicas=2 \
      --config retention.ms=604800000

    kafka-topics --create --if-not-exists --bootstrap-server $KAFKA_BROKER \
      --topic order.completed --partitions 3 --replication-factor 3 \
      --config min.insync.replicas=2 \
      --config retention.ms=604800000

    kafka-topics --create --if-not-exists --bootstrap-server $KAFKA_BROKER \
      --topic notifications --partitions 3 --replication-factor 3 \
      --config min.insync.replicas=2 \
      --config retention.ms=259200000

    echo "Kafka topics created successfully"
    kafka-topics --list --bootstrap-server $KAFKA_BROKER
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-init
  namespace: fritzy
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: kafka-topics
        image: confluentinc/cp-kafka:7.5.0
        command: ["/bin/bash", "/scripts/topics.sh"]
        volumeMounts:
        - name: kafka-topics
          mountPath: /scripts
      volumes:
      - name: kafka-topics
        configMap:
          name: kafka-topics
          defaultMode: 0755
