apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fritzy
data:
  ACCOUNT_SERVICE_URL: "http://account-service:8080"
  CATALOG_SERVICE_URL: "http://catalog-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  KAFKA_BROKERS: "kafka-0.kafka-headless:9092,kafka-1.kafka-headless:9092,kafka-2.kafka-headless:9092"
  KAFKA_CONSUMER_GROUP: "fritzy-services"
