apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fritzy-backend-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Varun5711/fritzy_backend.git
    targetRevision: develop
    path: infra/k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: fritzy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fritzy-backend-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Varun5711/fritzy_backend.git
    targetRevision: staging
    path: infra/k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: fritzy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fritzy-backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Varun5711/fritzy_backend.git
    targetRevision: main
    path: infra/k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: fritzy
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fritzy-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Varun5711/fritzy_backend.git
    targetRevision: main
    path: infra/k8s/monitoring
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
