apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: fritzy
data:
  ENVIRONMENT: "staging"
  LOG_LEVEL: "info"
  ACCOUNT_SERVICE_URL: "http://account-service:8080"
  CATALOG_SERVICE_URL: "http://catalog-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  RATE_LIMIT: "5000"
  CACHE_TTL: "600"
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: fritzy
type: Opaque
stringData:
  POSTGRES_USER: "staging_user"
  POSTGRES_PASSWORD: "staging_password_change_me"
  POSTGRES_DB: "fritzy_staging"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: fritzy
spec:
  replicas: 3
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql-hpa
  namespace: fritzy
spec:
  minReplicas: 3
  maxReplicas: 10
